language: cpp

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export CC=${CC_COMPILER}
      export CXX=${CXX_COMPILER}

      alias python=python3
      sudo pip install conan
    fi

  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update
      brew install conan
      brew install qt5
      brew link --force qt5
    fi

  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - conan remote add owl https://api.bintray.com/conan/zethon/owl

matrix:
  include:
    - os: osx
      osx_image: xcode10
      compiler: clang
      env: CONFIG=Release
    - os: osx
      osx_image: xcode10
      compiler: clang
      env: CONFIG=Debug
    - os: linux
      dist: bionic
      sudo: required
      compiler: gcc
      language: python
      python: "3.6"
      env:
        - CC_COMPILER=gcc-7
        - CXX_COMPILER=g++-7
        - CONFIG=RelWithDebInfo
      addons:
        apt:
          packages:
            - gcc-7
            - g++-7
            - build-essential
            - qt512base
            - qt512tools
            - qt512webengine
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: "ppa:beineri/opt-qt-5.12.3-bionic"

script:
  - mkdir build
  - cd build

  # Linux
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      # NOTE: Ideally the "libstdc++" here would be "libstdc++11" but that seems to cause problems
      # on Travis because they're using an old version of Ubuntu. Of course the "libstdc++" might 
      # work as-is if Hunspell was built using the same standard library but as it stands now, my 
      # Conan libs use "libstdc++11" and I don't feel like digging into this anymore right now in 
      # order to fix that.
      conan install .. --build missing -s compiler=gcc -s compiler.libcxx=libstdc++ -s compiler.version=7
      source /opt/qt512/bin/qt512-env.sh;
      cmake .. -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5 -DCONAN_LIBCXX=libstdc++ -DBUILD_TEST=ON -DBUILD_GUI=OFF 
    fi

  # OSX
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      conan install .. --build missing
      cmake .. -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5 -DBUILD_TEST=ON -DBUILD_CONSOLE=ON
    fi
  
  - cmake --build . --config "${CONFIG}" -- -j3 VERBOSE=1

after_success:
  - ctest -C "${CONFIG}"

notifactions:
  email:
    recipients:
      - aclaure@gmail.com
    on_success: never
    on_failre: always
