language: cpp

before_install:


matrix:
    - os: osx
      osx_image: xcode10

script:
  - pip install conan
  - conan install ./src

notifactions:
  email:
    recipients:
      - aclaure@gmail.com
    on_success: never
    on_failre: always