language: cpp

before_install:
  - echo $TRAVIS_OS_NAME
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install conan; fi

matrix:
  include:
    - os: osx
      osx_image: xcode10

script:
  - conan install ./src

notifactions:
  email:
    recipients:
      - aclaure@gmail.com
    on_success: never
    on_failre: always