language: cpp

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update
      brew install conan
      brew install qt5
      brew link --force qt5
    fi

  - conan remote add owl https://api.bintray.com/conan/zethon/owl
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

matrix:
  include:
    # - os: osx
    #   osx_image: xcode10
    #   compiler: clang
    #   env: CONFIG=Release
    # - os: osx
    #   osx_image: xcode10
    #   compiler: clang
    #   env: CONFIG=Debug
    - os: linux
      dist: trusty
      sudo: required
      compiler: g++
      env: CONFIG=RelWithDebInfo CXX_COMPILER=g++-6

script:
  - mkdir build
  - cd build
  - conan install .. --build missing
  - cmake .. -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5 -DBUILD_TEST=true
  - cmake --build . --config "${CONFIG}" -- -j3

after_success:
  - ctest -C "${CONFIG}"

notifactions:
  email:
    recipients:
      - aclaure@gmail.com
    on_success: never
    on_failre: always