language: cpp

before_install:
# OSX setup
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install conan; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link --force qt5; fi

install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      # sudo pip install --upgrade pip
      # sudo pip install conan_package_tools --upgrade
      sudo pip install conan
    fi

  - conan remote add owl https://api.bintray.com/conan/zethon/owl
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - export CXX=${CXX_COMPILER}

matrix:
  include:
    # - os: osx
    #   osx_image: xcode10
    #   compiler: clang
    #   env: CONFIG=Release
    # - os: osx
    #   osx_image: xcode10
    #   compiler: clang
    #   env: CONFIG=Debug
    - os: linux
      dist: trusty
      sudo: required
      env:
        - CC_COMPILER=gcc-7
        - CXX_COMPILER=g++-7
        - BUILD_TYPE=RelWithDebInfo
      addons:
        apt:
          packages:
            - python3
            - gcc-7
            - g++-7
          sources:
            - ubuntu-toolchain-r-test

script:
  - mkdir build
  - cd build
  - conan install .. --build missing
  - cmake .. -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5 -DBUILD_TEST=true
  - cmake --build . --config "${CONFIG}" -- -j3

after_success:
  - ctest -C "${CONFIG}"

notifactions:
  email:
    recipients:
      - aclaure@gmail.com
    on_success: never
    on_failre: always