language: cpp

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo pip install conan
      alias python=python3
      sudo binutils-config x86_64-pc-linux-gnu-2.29.1
    fi

  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update
      brew install conan
      brew install qt5
      brew link --force qt5
    fi

  - conan remote add owl https://api.bintray.com/conan/zethon/owl
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - export CXX=${CXX_COMPILER}

matrix:
  include:
    # - os: osx
    #   osx_image: xcode10
    #   compiler: clang
    #   env: CONFIG=Release
    # - os: osx
    #   osx_image: xcode10
    #   compiler: clang
    #   env: CONFIG=Debug
    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: "3.6"
      env:
        - CC_COMPILER=gcc-7
        - CXX_COMPILER=g++-7
        - BUILD_TYPE=RelWithDebInfo
      addons:
        apt:
          packages:
            - qt510base
            - qt510tools
            - qt510webengine
            - gcc-7
            - g++-7
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: "ppa:beineri/opt-qt-5.10.1-trusty"

script:
  - source /opt/qt510/bin/qt510-env.sh;
  - mkdir build
  - cd build
  - conan install .. --build missing -s compiler=gcc -s compiler.libcxx=libstdc++ -s compiler.version=7
  - cmake .. -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5 -DBUILD_TEST=true
  - cmake --build . --config "${CONFIG}" -- -j3

after_success:
  - ctest -C "${CONFIG}"

notifactions:
  email:
    recipients:
      - aclaure@gmail.com
    on_success: never
    on_failre: always