language: cpp

before_install:
  - echo $TRAVIS_OS_NAME
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install conan; fi

matrix:
  include:
    - os: osx
      osx_image: xcode10

script:
  - conan install ./src -s compiler=apple-clang -s compiler.version=10.0 -s compiler.libcxx=libc++

notifactions:
  email:
    recipients:
      - aclaure@gmail.com
    on_success: never
    on_failre: always