language: cpp

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install conan; fi

matrix:
  include:
    - os: osx
      osx_image: xcode10
      compiler: clang

script:
  - conan remote add owl https://api.bintray.com/conan/zethon/owl
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - conan profile show default
  - conan install ./src
  # - conan install ./src -s compiler=apple-clang -s compiler.version=10.0 -s compiler.libcxx=libc++ --build libcurl

notifactions:
  email:
    recipients:
      - aclaure@gmail.com
    on_success: never
    on_failre: always