version: 0.7.{build}

image: 
 - Visual Studio 2017

environment:
  matrix:
    - CONFIG: Release
    - CONFIG: RelWithDebInfo

install:
  - echo "Downloading conan..."
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan
  - conan remote add owl https://api.bintray.com/conan/zethon/owl
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

build_script:
  - mkdir build
  - cd build
  - conan install .. --build missing
  - cmake .. "-GVisual Studio 15 2017 Win64" -DCMAKE_PREFIX_PATH=C:/Qt/5.10.1/msvc2017_64 -DBUILD_TEST=true
  - cmake --build . --config "%CONFIG%" -- /maxcpucount:4
  - set PATH=%PATH%;C:\Qt\5.10.1\msvc2017_64\bin
  - ctest -VV -C "%CONFIG%"
