version: 0.7.{build}

image: 
 - Visual Studio 2017

configuration:
  - Debug
  - Release

install:
  - echo "Downloading conan..."
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - set PATH=%PATH%;C:\Qt\5.11\msvc2017_64\bin
  - pip.exe install conan
  - conan remote add owl https://api.bintray.com/conan/zethon/owl
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

build_script:
  - mkdir build
  - cd build
  - conan install .. --build missing -s build_type=%configuration%
  - cmake .. -DCMAKE_BUILD_TYPE=%CONFIG% "-GVisual Studio 15 2017 Win64" -DCMAKE_PREFIX_PATH=C:/Qt/5.11/msvc2017_64 -DBUILD_GUI=ON -DBUILD_TEST=ON -DBUILD_CONSOLE=OFF
  - cmake --build . -- /maxcpucount:4

test_script:
  - ctest -VV -C "%CONFIG%" --output-on-failure
