version: 0.7.{build}

environment:
  matrix:
    - TOOLCHAIN: "vs-15-2017-win64"
      CONFIG: Release
    - TOOLCHAIN: "vs-15-2017-win64"
      CONFIG: RelWithDebInfo

install:
  - echo "Downloading conan..."
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan
  # - conan user # Create the conan data directory
  - conan remote add owl https://api.bintray.com/conan/zethon/owl
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

build_script:
  - mkdir build
  - cd build
  - conan install ../src
  - cmake ../src "-GVisual Studio 15 2017 Win64" -DCMAKE_PREFIX_PATH=C:/Qt/5.11.1/msvc2017_64
  - cmake --build . --config "%CONFIG%" -- /maxcpucount:4
