image: 
 - Visual Studio 2017

configuration:
  # - Debug
  - Release

environment:
  ftp_password:
    secure: edNpE3aPKyOzzhE2sb6CKg==

install:
  - echo "Environment"
  - set
  - cmake --version
  - echo "Downloading conan..."
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan
  - conan --version
  - conan remote add owl https://api.bintray.com/conan/zethon/owl
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

build_script:
  - mkdir build
  - cd build
  - conan install .. --build missing -s build_type=%configuration%
  - cmake .. -DCMAKE_BUILD_TYPE=%configuration% "-GVisual Studio 15 2017 Win64" -DCMAKE_PREFIX_PATH=C:/Qt/5.11/msvc2017_64 -DBUILD_GUI=ON -DBUILD_CONSOLE=ON -DBUILD_TEST=ON
  - cmake --build . --config %configuration% -- /maxcpucount:4

test_script:
  - set PATH=%PATH%;C:\Qt\5.11\msvc2017_64\bin
  - ctest -VV -C "%configuration%" --schedule-random --output-on-failure

after_test:
  - if "%configuration%"=="Release" ..\installers\windows\build.cmd

artifacts:
  # References here need to have "build\" prepended since 
  # the context here is from the original build folder 
  # before we "cd build" 
  - path: build\owl-*.exe
    name: OwlInstallers

deploy:
  provider: FTP
  protocol: ftp
  host: ftp.owlclient.com
  username: admin@owlclient.com
  password:
    secure: P7iZrcnNk20p8pi9kuUktg==
  folder: /public_html/artifacts
  on:
    branch: master
    configuration: Release

notifications:
  - provider: Email
    to:
      - builds@owl.dog
    on_build_success: false
    on_build_failure: true